name: Pull Request

on:
  pull_request:
    branches:
    - dev
    # types:
    # - opened

jobs:
  schedule_publish:
    name: Schedule publish

    runs-on: ubuntu-latest

    steps:
    - name: Check pr body
      shell: bash
      run: |
        function yaml2json()
        {
            ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' $*
        }

        echo ${{ toJSON(github.event.pull_request.body) }} | yaml2json | jq '.published'
        echo ${{ toJSON(github.event.pull_request.body) }} | yaml2json | jq '.twitter'
        echo ${{ toJSON(github.event.pull_request.body) }} | yaml2json | jq '.facebook'
        echo ${{ toJSON(github.event.pull_request.body) }} | yaml2json | jq '.linkedin'

    - name: Check event payload
      shell: bash
      run: |
        echo ${{ toJSON(github.event) }}
