name: Pull Request

on:
  pull_request:
    branches:
    - dev
    types:
    - opened
    # - edited
    # - synchronize

jobs:
  schedule_publish:
    name: Schedule publish

    runs-on: ubuntu-latest

    steps:
    - name: Install niet
      shell: bash
      run: |
        sudo pip install -U niet

    - name: Check pr body
      id: prbody
      shell: bash
      run: |
        echo ::set-output name=published::$(echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!published: !!g' | sed 's!\\r\\n!!g')

    - name: Check environment variables
      shell: bash
      run: |
        echo "Published: ${{ steps.prbody.outputs.published }}"

    # - name: Check event payload
    #   shell: bash
    #   run: |
    #     echo ${{ toJSON(github.event) }}
