name: Pull Request

on:
  pull_request:
    branches:
    - dev
    # types:
    # - opened

jobs:
  schedule_publish:
    name: Schedule publish

    runs-on: ubuntu-latest

    steps:
    - name: Install niet
      shell: bash
      run: |
        sudo pip install -U niet

    - name: Check pr body
      shell: bash
      run: |
        echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!\\r\\n!\r\n!g' | niet '.published'
        echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!\\r\\n!\r\n!g' | niet '.twitter'
        echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!\\r\\n!\r\n!g' | niet '.facebook'
        echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!\\r\\n!\r\n!g' | niet '.linkedin'

    - name: Check event payload
      shell: bash
      run: |
        echo ${{ toJSON(github.event) }}
