name: Pull Request

on:
  pull_request:
    branches:
    - dev
    types:
    - opened
    - edited
    - synchronize

jobs:
  schedule_publish:
    name: Schedule publish

    runs-on: ubuntu-latest

    steps:
    - name: Install niet
      shell: bash
      run: |
        sudo pip install -U niet

    - name: Check pr body
      id: prbody
      shell: bash
      run: |
        echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!\\r\\n!\r\n!g' | niet . -f json

    # - name: Check pr body
    #   id: prbody
    #   shell: bash
    #   run: |
    #     echo ::set-output name=published::$(echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!\\r\\n!\r\n!g' | niet '.published')
    #     echo ::set-output name=twitterMessage::$(echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!\\r\\n!\r\n!g' | niet '.twitter')
    #     echo ::set-output name=facebookMessage::$(echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!\\r\\n!\r\n!g' | niet '.facebook')
    #     echo ::set-output name=linkedInMessage::$(echo ${{ toJSON(github.event.pull_request.body) }} | sed 's!\\r\\n!\r\n!g' | niet '.linkedin')

    # - name: Check environment variables
    #   shell: bash
    #   run: |
    #     echo "Published: ${{ steps.prbody.outputs.published }}"
    #     echo "Twitter Message: ${{ steps.prbody.outputs.twitterMessage }}"
    #     echo "Facebook Message: ${{ steps.prbody.outputs.facebookMessage }}"
    #     echo "LinkedIn Message: ${{ steps.prbody.outputs.linkedInMessage }}"

    - name: Check event payload
      shell: bash
      run: |
        echo ${{ toJSON(github.event) }}
