name: Pull Request

on:
  pull_request:
    branches:
    - dev

jobs:
  schedule_publish:
    name: Schedule publish

    runs-on: ubuntu-latest

    steps:
    - name: Check event payload
      shell: bash
      run: |
        echo ${{ toJSON(github.event) }}

    - name: Check event payload
      shell: bash
      run: |
        echo ${{ toJSON(github.event.pull_request.body) }}
